version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: shippings-db
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    container_name: shippings-redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-network
    volumes:
      - redis_data:/data

  app:
    container_name: shippings-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:5000
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
