CREATE TABLE `order` (
    ord_id INT AUTO_INCREMENT PRIMARY KEY,
    ord_sender_id INT NOT NULL,
    ord_receiver_id INT NOT NULL,
    ord_product_category VARCHAR(255) NOT NULL,
    ord_weight_grams VARCHAR(255) NOT NULL,
    ord_target_address VARCHAR(500) NOT NULL,
    ord_product_description TEXT NOT NULL,
    ord_dimension_x INT NOT NULL,
    ord_dimension_y INT NOT NULL,
    ord_dimension_z INT NOT NULL,
    ord_quantity INT NOT NULL,
    ord_status VARCHAR(100) NOT NULL,
    ord_transporter_id INT NULL,
    ord_route_id INT NULL,
    ord_source_city_id INT NOT NULL,
    ord_target_city_id INT NOT NULL,
    ord_latitude DECIMAL(10, 7) NULL,
    ord_longitude DECIMAL(10, 7) NULL,
    ord_solved_address VARCHAR(500) NULL,
    ord_solved_city VARCHAR(255) NULL,
    ord_assigned_date DATETIME NULL,
    ord_expected_reach_date DATETIME NULL,
    ord_actual_reach_date DATETIME NULL,
    ord_short_id VARCHAR(50) NOT NULL,
    ord_vehicle_id INT NULL,
    FOREIGN KEY (ord_sender_id) REFERENCES user(usr_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_receiver_id) REFERENCES user(usr_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_source_city_id) REFERENCES city(cit_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_target_city_id) REFERENCES city(cit_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_transporter_id) REFERENCES transporter(tra_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_route_id) REFERENCES route(rou_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ord_vehicle_id) REFERENCES vehicle(veh_id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY (ord_short_id)
);