INSERT INTO city (cit_name)
VALUES ('New York'),
    ('Los Angeles'),
    ('Chicago'),
    ('Houston'),
    ('Phoenix'),
    ('Philadelphia'),
    ('San Antonio'),
    ('San Diego'),
    ('Dallas'),
    ('San Jose'),
    ('Austin'),
    ('Jacksonville'),
    ('Fort Worth'),
    ('Columbus'),
    ('Indianapolis'),
    ('Charlotte'),
    ('San Francisco'),
    ('Seattle'),
    ('Denver'),
    ('Washington');