CREATE TABLE `order` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    product_category VARCHAR(255) NOT NULL,
    weight_grams VARCHAR(255) NOT NULL,
    target_address VARCHAR(500) NOT NULL,
    product_description TEXT NOT NULL,
    dimension_x INT NOT NULL,
    dimension_y INT NOT NULL,
    dimension_z INT NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(100) NOT NULL,
    transporter_id INT NULL,
    route_id INT NULL,
    source_city_id INT NOT NULL,
    target_city_id INT NOT NULL,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    solved_address VARCHAR(500) NOT NULL,
    solved_city VARCHAR(255) NOT NULL,
    assigned_date DATETIME NULL,
    expected_reach_date DATETIME NULL,
    actual_reach_date DATETIME NULL,
    short_id VARCHAR(50) NOT NULL,
    vehicle_id INT NOT NULL,
    FOREIGN KEY (sender_id) REFERENCES user(usr_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES user(usr_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (source_city_id) REFERENCES city(cit_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (target_city_id) REFERENCES city(cit_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (transporter_id) REFERENCES transporter(tra_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (route_id) REFERENCES route(rou_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(veh_id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY (short_id)
);