CREATE TABLE city_route (
    cit_rou_id INT AUTO_INCREMENT PRIMARY KEY,
    rou_id INT NOT NULL,
    cit_id INT NOT NULL,
    FOREIGN KEY (rou_id) REFERENCES route(rou_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cit_id) REFERENCES city(cit_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;